/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package verwalten;

import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import org.netbeans.lib.awtextra.*;
import java.awt.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import palatte.*;

/**
 *
 * @author XuanN
 */
public class Verwalten extends javax.swing.JFrame {

    /**
     * Creates new form Verwalten
     */
    int menuSelected = 0;
    MouseEvent e = null;
    int menuLoactionX = 0;
    
    public Verwalten() {
        initComponents();

        cmbtn_trang_chuMouseEntered(e);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_main = new javax.swing.JPanel();
        pnl_taskbar = new javax.swing.JPanel();
        cbtn_close = new palatte.Custom_button();
        cbtn_minimize = new palatte.Custom_button();
        pnl_header = new javax.swing.JPanel();
        lbl_logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnl_content = new javax.swing.JPanel();
        pnl_menu = new javax.swing.JPanel();
        cmbtn_trang_chu = new palatte.Custom_menu_button();
        cmbtn_sinh_vien = new palatte.Custom_menu_button();
        cmbtn_lop = new palatte.Custom_menu_button();
        cmbtn_nganh = new palatte.Custom_menu_button();
        cmbtn_giao_vien = new palatte.Custom_menu_button();
        cmbtn_mon = new palatte.Custom_menu_button();
        jLabel9 = new javax.swing.JLabel();
        cmbtn_menu = new palatte.Custom_menu_button();
        cmbtn_menu1 = new palatte.Custom_menu_button();
        tbpnl_main = new javax.swing.JTabbedPane();
        pnl_home = new javax.swing.JPanel();
        lbl_sinh_vien = new javax.swing.JLabel();
        lbl_lop_hoc = new javax.swing.JLabel();
        lbl_nganh_hoc = new javax.swing.JLabel();
        lbl_giao_vien = new javax.swing.JLabel();
        lbl_mon_hoc = new javax.swing.JLabel();
        lbl_txt_sinh_vien = new javax.swing.JLabel();
        lbl_txt_lop = new javax.swing.JLabel();
        lbl_txt_nganh = new javax.swing.JLabel();
        lbl_txt_giao_vien = new javax.swing.JLabel();
        lbl_txt_mon = new javax.swing.JLabel();
        lbl_txt_sinh_vien1 = new javax.swing.JLabel();
        lbl_txt_lop1 = new javax.swing.JLabel();
        lbl_txt_nganh1 = new javax.swing.JLabel();
        lbl_txt_giao_vien1 = new javax.swing.JLabel();
        lbl_txt_mon1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pnl_sinh_vien = new javax.swing.JPanel();
        cmbtn_chi_tiet_sv = new palatte.Custom_menu_button();
        cmbtn_xoa_sv = new palatte.Custom_menu_button();
        cmbtn_sx_sv = new palatte.Custom_menu_button();
        cmbtn_add_sv = new palatte.Custom_menu_button();
        ccbb_SVchon_nganh = new palatte.Custom_cbb();
        ccbb_SVchon_xep_hang = new palatte.Custom_cbb();
        ccbb_SVchon_lop = new palatte.Custom_cbb();
        ccbb_SV_chon_gioi_tinh = new palatte.Custom_cbb();
        spnl_sv = new javax.swing.JScrollPane();
        ctb_sv = new palatte.Custom_tb();
        pnl_lop = new javax.swing.JPanel();
        cmbtn_chi_tiet_lop = new palatte.Custom_menu_button();
        cmbtn_xoa_lop = new palatte.Custom_menu_button();
        cmbtn_add_lop = new palatte.Custom_menu_button();
        ccbb_Lop_chon_nganh = new palatte.Custom_cbb();
        spnl_lop = new javax.swing.JScrollPane();
        ctb_lop = new palatte.Custom_tb();
        pnl_nganh_hoc = new javax.swing.JPanel();
        cmbtn_chi_tiet_nganh_hoc = new palatte.Custom_menu_button();
        cmbtn_xoa_nganh_hoc = new palatte.Custom_menu_button();
        cmbtn_add_nganh_hoc = new palatte.Custom_menu_button();
        spnl_nganh = new javax.swing.JScrollPane();
        ctb_nganh = new palatte.Custom_tb();
        pnl_giao_vien = new javax.swing.JPanel();
        cmbtn_chi_tiet_GV = new palatte.Custom_menu_button();
        cmbtn_xoa_GV = new palatte.Custom_menu_button();
        ccbb_chon_gioi_tinh_GV = new palatte.Custom_cbb();
        cmbtn_sx_GV = new palatte.Custom_menu_button();
        cmbtn_add_GV = new palatte.Custom_menu_button();
        spnl_GV = new javax.swing.JScrollPane();
        ctb_GV = new palatte.Custom_tb();
        pnl_mon_hoc = new javax.swing.JPanel();
        cmbtn_chi_tiet_mon_hoc = new palatte.Custom_menu_button();
        cmbtn_xoa_mon_hoc = new palatte.Custom_menu_button();
        cmbtn_add_mon_hoc = new palatte.Custom_menu_button();
        spnl_mon_hoc = new javax.swing.JScrollPane();
        custom_tb1 = new palatte.Custom_tb();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Verwalten");
        setUndecorated(true);
        setResizable(false);

        pnl_main.setBackground(new java.awt.Color(0, 0, 51));
        pnl_main.setMinimumSize(new java.awt.Dimension(1400, 900));
        pnl_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_taskbar.setBackground(new java.awt.Color(255, 255, 255));
        pnl_taskbar.setMinimumSize(new java.awt.Dimension(1400, 30));
        pnl_taskbar.setPreferredSize(new java.awt.Dimension(1400, 30));
        pnl_taskbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbtn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/close.png"))); // NOI18N
        cbtn_close.setMaximumSize(new java.awt.Dimension(30, 30));
        cbtn_close.setMinimumSize(new java.awt.Dimension(30, 30));
        cbtn_close.setPreferredSize(new java.awt.Dimension(30, 30));
        cbtn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbtn_closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbtn_closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cbtn_closeMouseExited(evt);
            }
        });
        pnl_taskbar.add(cbtn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 0, -1, -1));

        cbtn_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/minimize.png"))); // NOI18N
        cbtn_minimize.setMaximumSize(new java.awt.Dimension(30, 30));
        cbtn_minimize.setMinimumSize(new java.awt.Dimension(30, 30));
        cbtn_minimize.setPreferredSize(new java.awt.Dimension(30, 30));
        cbtn_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbtn_minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbtn_minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cbtn_minimizeMouseExited(evt);
            }
        });
        pnl_taskbar.add(cbtn_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 0, -1, -1));

        pnl_main.add(pnl_taskbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnl_header.setBackground(new java.awt.Color(255, 138, 0));
        pnl_header.setMaximumSize(new java.awt.Dimension(1400, 90));
        pnl_header.setMinimumSize(new java.awt.Dimension(1400, 90));
        pnl_header.setPreferredSize(new java.awt.Dimension(1400, 90));
        pnl_header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/VERWALTEN.png"))); // NOI18N
        pnl_header.add(lbl_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 4, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("VERWALTET");
        pnl_header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 16, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ứng Dụng Quản Lý Sinh Viên");
        pnl_header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 55, -1, -1));

        pnl_main.add(pnl_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        pnl_content.setBackground(new java.awt.Color(0, 0, 51));
        pnl_content.setMaximumSize(new java.awt.Dimension(1400, 780));
        pnl_content.setMinimumSize(new java.awt.Dimension(1400, 780));
        pnl_content.setPreferredSize(new java.awt.Dimension(1400, 780));
        pnl_content.setRequestFocusEnabled(false);
        pnl_content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_menu.setBackground(new java.awt.Color(26, 24, 24));
        pnl_menu.setMaximumSize(new java.awt.Dimension(236, 800));
        pnl_menu.setMinimumSize(new java.awt.Dimension(236, 800));
        pnl_menu.setPreferredSize(new java.awt.Dimension(236, 780));
        pnl_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbtn_trang_chu.setForeground(new java.awt.Color(255, 255, 255));
        cmbtn_trang_chu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/home.png"))); // NOI18N
        cmbtn_trang_chu.setText("            Trang chủ");
        cmbtn_trang_chu.setActionCommand("Trang chủ");
        cmbtn_trang_chu.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cmbtn_trang_chu.setIconTextGap(36);
        cmbtn_trang_chu.setMaximumSize(new java.awt.Dimension(236, 40));
        cmbtn_trang_chu.setMinimumSize(new java.awt.Dimension(236, 40));
        cmbtn_trang_chu.setPreferredSize(new java.awt.Dimension(236, 40));
        cmbtn_trang_chu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbtn_trang_chuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbtn_trang_chuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbtn_trang_chuMouseExited(evt);
            }
        });
        pnl_menu.add(cmbtn_trang_chu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 78, -1, -1));

        cmbtn_sinh_vien.setForeground(new java.awt.Color(255, 255, 255));
        cmbtn_sinh_vien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/student.png"))); // NOI18N
        cmbtn_sinh_vien.setText("            Sinh viên");
        cmbtn_sinh_vien.setActionCommand("Trang chủ");
        cmbtn_sinh_vien.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cmbtn_sinh_vien.setIconTextGap(42);
        cmbtn_sinh_vien.setMaximumSize(new java.awt.Dimension(236, 40));
        cmbtn_sinh_vien.setMinimumSize(new java.awt.Dimension(236, 40));
        cmbtn_sinh_vien.setPreferredSize(new java.awt.Dimension(236, 40));
        cmbtn_sinh_vien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbtn_sinh_vienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbtn_sinh_vienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbtn_sinh_vienMouseExited(evt);
            }
        });
        pnl_menu.add(cmbtn_sinh_vien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 129, -1, -1));

        cmbtn_lop.setForeground(new java.awt.Color(255, 255, 255));
        cmbtn_lop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/class_1.png"))); // NOI18N
        cmbtn_lop.setText("            Lớp học");
        cmbtn_lop.setActionCommand("Trang chủ");
        cmbtn_lop.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cmbtn_lop.setIconTextGap(48);
        cmbtn_lop.setMaximumSize(new java.awt.Dimension(236, 40));
        cmbtn_lop.setMinimumSize(new java.awt.Dimension(236, 40));
        cmbtn_lop.setPreferredSize(new java.awt.Dimension(236, 40));
        cmbtn_lop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbtn_lopMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbtn_lopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbtn_lopMouseExited(evt);
            }
        });
        pnl_menu.add(cmbtn_lop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        cmbtn_nganh.setForeground(new java.awt.Color(255, 255, 255));
        cmbtn_nganh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/major_1.png"))); // NOI18N
        cmbtn_nganh.setText("            Ngành học");
        cmbtn_nganh.setActionCommand("Trang chủ");
        cmbtn_nganh.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cmbtn_nganh.setIconTextGap(32);
        cmbtn_nganh.setMaximumSize(new java.awt.Dimension(236, 40));
        cmbtn_nganh.setMinimumSize(new java.awt.Dimension(236, 40));
        cmbtn_nganh.setPreferredSize(new java.awt.Dimension(236, 40));
        cmbtn_nganh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbtn_nganhMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbtn_nganhMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbtn_nganhMouseExited(evt);
            }
        });
        pnl_menu.add(cmbtn_nganh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 231, -1, -1));

        cmbtn_giao_vien.setForeground(new java.awt.Color(255, 255, 255));
        cmbtn_giao_vien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/teacher_1.png"))); // NOI18N
        cmbtn_giao_vien.setText("            Giáo viên");
        cmbtn_giao_vien.setActionCommand("Trang chủ");
        cmbtn_giao_vien.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cmbtn_giao_vien.setIconTextGap(36);
        cmbtn_giao_vien.setMaximumSize(new java.awt.Dimension(236, 40));
        cmbtn_giao_vien.setMinimumSize(new java.awt.Dimension(236, 40));
        cmbtn_giao_vien.setPreferredSize(new java.awt.Dimension(236, 40));
        cmbtn_giao_vien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbtn_giao_vienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbtn_giao_vienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbtn_giao_vienMouseExited(evt);
            }
        });
        pnl_menu.add(cmbtn_giao_vien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 282, -1, -1));

        cmbtn_mon.setForeground(new java.awt.Color(255, 255, 255));
        cmbtn_mon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/subject_1.png"))); // NOI18N
        cmbtn_mon.setText("            Môn học");
        cmbtn_mon.setActionCommand("Trang chủ");
        cmbtn_mon.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        cmbtn_mon.setIconTextGap(42);
        cmbtn_mon.setMaximumSize(new java.awt.Dimension(236, 40));
        cmbtn_mon.setMinimumSize(new java.awt.Dimension(236, 40));
        cmbtn_mon.setPreferredSize(new java.awt.Dimension(236, 40));
        cmbtn_mon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbtn_monMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbtn_monMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbtn_monMouseExited(evt);
            }
        });
        pnl_menu.add(cmbtn_mon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 333, -1, -1));

        jLabel9.setFont(new java.awt.Font("Californian FB", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("@Nhóm 3");
        pnl_menu.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 743, -1, -1));

        cmbtn_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/menu.png"))); // NOI18N
        cmbtn_menu.setMaximumSize(new java.awt.Dimension(46, 30));
        cmbtn_menu.setMinimumSize(new java.awt.Dimension(46, 30));
        cmbtn_menu.setPreferredSize(new java.awt.Dimension(46, 30));
        cmbtn_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbtn_menuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbtn_menuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbtn_menuMouseExited(evt);
            }
        });
        pnl_menu.add(cmbtn_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 28, -1, -1));

        pnl_content.add(pnl_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-236, 0, -1, -1));
        JPopupMenu popup = new JPopupMenu();
        pnl_menu.setComponentPopupMenu(popup);

        cmbtn_menu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/menu.png"))); // NOI18N
        cmbtn_menu1.setMaximumSize(new java.awt.Dimension(46, 30));
        cmbtn_menu1.setMinimumSize(new java.awt.Dimension(46, 30));
        cmbtn_menu1.setPreferredSize(new java.awt.Dimension(46, 30));
        cmbtn_menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbtn_menu1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbtn_menu1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbtn_menu1MouseExited(evt);
            }
        });
        pnl_content.add(cmbtn_menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 28, -1, -1));

        tbpnl_main.setMaximumSize(new java.awt.Dimension(1400, 780));
        tbpnl_main.setMinimumSize(new java.awt.Dimension(1400, 780));
        tbpnl_main.setPreferredSize(new java.awt.Dimension(1400, 780));

        pnl_home.setBackground(new java.awt.Color(0, 0, 51));
        pnl_home.setMaximumSize(new java.awt.Dimension(1400, 780));
        pnl_home.setMinimumSize(new java.awt.Dimension(1400, 780));
        pnl_home.setPreferredSize(new java.awt.Dimension(1400, 780));
        pnl_home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_sinh_vien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/L_student.png"))); // NOI18N
        lbl_sinh_vien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_sinh_vienMouseClicked(evt);
            }
        });
        pnl_home.add(lbl_sinh_vien, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 50, -1, -1));

        lbl_lop_hoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/class.png"))); // NOI18N
        lbl_lop_hoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_lop_hocMouseClicked(evt);
            }
        });
        pnl_home.add(lbl_lop_hoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 50, -1, -1));

        lbl_nganh_hoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/major.png"))); // NOI18N
        lbl_nganh_hoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_nganh_hocMouseClicked(evt);
            }
        });
        pnl_home.add(lbl_nganh_hoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(653, 50, -1, -1));

        lbl_giao_vien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/teacher.png"))); // NOI18N
        lbl_giao_vien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_giao_vienMouseClicked(evt);
            }
        });
        pnl_home.add(lbl_giao_vien, new org.netbeans.lib.awtextra.AbsoluteConstraints(901, 50, -1, -1));

        lbl_mon_hoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/subject.png"))); // NOI18N
        lbl_mon_hoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_mon_hocMouseClicked(evt);
            }
        });
        pnl_home.add(lbl_mon_hoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1149, 50, -1, -1));

        lbl_txt_sinh_vien.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lbl_txt_sinh_vien.setForeground(new java.awt.Color(255, 255, 255));
        lbl_txt_sinh_vien.setText("Tính năng thông");
        pnl_home.add(lbl_txt_sinh_vien, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 236, -1, -1));

        lbl_txt_lop.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lbl_txt_lop.setForeground(new java.awt.Color(255, 255, 255));
        lbl_txt_lop.setText("lý lớp học");
        pnl_home.add(lbl_txt_lop, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 265, -1, -1));

        lbl_txt_nganh.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lbl_txt_nganh.setForeground(new java.awt.Color(255, 255, 255));
        lbl_txt_nganh.setText("lý ngành học");
        pnl_home.add(lbl_txt_nganh, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 265, -1, -1));

        lbl_txt_giao_vien.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lbl_txt_giao_vien.setForeground(new java.awt.Color(255, 255, 255));
        lbl_txt_giao_vien.setText("tin giáo viên");
        pnl_home.add(lbl_txt_giao_vien, new org.netbeans.lib.awtextra.AbsoluteConstraints(933, 265, -1, -1));

        lbl_txt_mon.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lbl_txt_mon.setForeground(new java.awt.Color(255, 255, 255));
        lbl_txt_mon.setText("lý môn học");
        pnl_home.add(lbl_txt_mon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1187, 265, -1, -1));

        lbl_txt_sinh_vien1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lbl_txt_sinh_vien1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_txt_sinh_vien1.setText("tin sinh viên");
        pnl_home.add(lbl_txt_sinh_vien1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 265, -1, -1));

        lbl_txt_lop1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lbl_txt_lop1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_txt_lop1.setText("Tính năng quản");
        pnl_home.add(lbl_txt_lop1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 236, -1, -1));

        lbl_txt_nganh1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lbl_txt_nganh1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_txt_nganh1.setText("Tính năng quản");
        pnl_home.add(lbl_txt_nganh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 236, -1, -1));

        lbl_txt_giao_vien1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lbl_txt_giao_vien1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_txt_giao_vien1.setText("Tính năng thông");
        pnl_home.add(lbl_txt_giao_vien1, new org.netbeans.lib.awtextra.AbsoluteConstraints(913, 236, -1, -1));

        lbl_txt_mon1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lbl_txt_mon1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_txt_mon1.setText("Tính năng quản");
        pnl_home.add(lbl_txt_mon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1163, 236, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VERWALTEN là ứng dụng quản lý sinh viên cơ bản được thiết kế để giúp các trường đại học và cao đẳng quản lý hiệu quả các hoạt");
        jLabel3.setMaximumSize(new java.awt.Dimension(1152, 96));
        jLabel3.setMinimumSize(new java.awt.Dimension(1152, 96));
        jLabel3.setPreferredSize(new java.awt.Dimension(1152, 96));
        pnl_home.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 350, -1, 40));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("động liên quan đến sinh viên. Với VERWALTEN, bạn có thể dễ dàng nhập, cập nhật và tra cứu thông tin sinh viên, lớp học, ngành \n");
        jLabel10.setMaximumSize(new java.awt.Dimension(1152, 96));
        jLabel10.setMinimumSize(new java.awt.Dimension(1152, 96));
        jLabel10.setPreferredSize(new java.awt.Dimension(1152, 96));
        pnl_home.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 390, -1, 40));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("học, giáo viên và môn học.");
        jLabel11.setMaximumSize(new java.awt.Dimension(1152, 96));
        jLabel11.setMinimumSize(new java.awt.Dimension(1152, 96));
        jLabel11.setPreferredSize(new java.awt.Dimension(1152, 96));
        pnl_home.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 430, -1, 40));

        tbpnl_main.addTab("home", pnl_home);

        pnl_sinh_vien.setBackground(new java.awt.Color(0, 0, 51));
        pnl_sinh_vien.setForeground(new java.awt.Color(255, 255, 255));
        pnl_sinh_vien.setMaximumSize(new java.awt.Dimension(1400, 780));
        pnl_sinh_vien.setMinimumSize(new java.awt.Dimension(1400, 780));
        pnl_sinh_vien.setPreferredSize(new java.awt.Dimension(1400, 780));
        pnl_sinh_vien.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbtn_chi_tiet_sv.setForeground(new java.awt.Color(255, 255, 255));
        cmbtn_chi_tiet_sv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Information.png"))); // NOI18N
        cmbtn_chi_tiet_sv.setText("Chi tiết");
        cmbtn_chi_tiet_sv.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbtn_chi_tiet_sv.setIconTextGap(24);
        cmbtn_chi_tiet_sv.setMaximumSize(new java.awt.Dimension(130, 40));
        cmbtn_chi_tiet_sv.setMinimumSize(new java.awt.Dimension(130, 40));
        cmbtn_chi_tiet_sv.setPreferredSize(new java.awt.Dimension(130, 40));
        cmbtn_chi_tiet_sv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbtn_chi_tiet_svMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbtn_chi_tiet_svMouseExited(evt);
            }
        });
        pnl_sinh_vien.add(cmbtn_chi_tiet_sv, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 83, -1, 40));
        cmbtn_chi_tiet_sv.set_bgColor(new Color(0, 154, 249));

        cmbtn_xoa_sv.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cmbtn_xoa_sv.setForeground(new java.awt.Color(255, 255, 255));
        cmbtn_xoa_sv.setText("Xóa sinh viên");
        cmbtn_xoa_sv.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbtn_xoa_sv.setIconTextGap(24);
        cmbtn_xoa_sv.setMaximumSize(new java.awt.Dimension(130, 40));
        cmbtn_xoa_sv.setMinimumSize(new java.awt.Dimension(130, 40));
        cmbtn_xoa_sv.setPreferredSize(new java.awt.Dimension(130, 40));
        cmbtn_xoa_sv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbtn_xoa_svMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbtn_xoa_svMouseExited(evt);
            }
        });
        pnl_sinh_vien.add(cmbtn_xoa_sv, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 83, -1, 40));
        cmbtn_xoa_sv.set_bgColor(new Color(249, 0, 0));

        cmbtn_sx_sv.setForeground(new java.awt.Color(255, 255, 255));
        cmbtn_sx_sv.setText("Sắp xếp tên");
        cmbtn_sx_sv.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbtn_sx_sv.setIconTextGap(24);
        cmbtn_sx_sv.setMaximumSize(new java.awt.Dimension(180, 40));
        cmbtn_sx_sv.setMinimumSize(new java.awt.Dimension(180, 40));
        cmbtn_sx_sv.setPreferredSize(new java.awt.Dimension(180, 40));
        cmbtn_sx_sv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbtn_sx_svMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbtn_sx_svMouseExited(evt);
            }
        });
        cmbtn_sx_sv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtn_sx_svActionPerformed(evt);
            }
        });
        pnl_sinh_vien.add(cmbtn_sx_sv, new org.netbeans.lib.awtextra.AbsoluteConstraints(744, 83, -1, 40));
        cmbtn_sx_sv.set_bgColor(new Color(0, 154, 249));

        cmbtn_add_sv.setForeground(new java.awt.Color(255, 255, 255));
        cmbtn_add_sv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add.png"))); // NOI18N
        cmbtn_add_sv.setText("Thêm sinh viên");
        cmbtn_add_sv.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbtn_add_sv.setIconTextGap(24);
        cmbtn_add_sv.setMaximumSize(new java.awt.Dimension(180, 40));
        cmbtn_add_sv.setMinimumSize(new java.awt.Dimension(180, 40));
        cmbtn_add_sv.setPreferredSize(new java.awt.Dimension(180, 40));
        cmbtn_add_sv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbtn_add_svMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbtn_add_svMouseExited(evt);
            }
        });
        cmbtn_add_sv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtn_add_svActionPerformed(evt);
            }
        });
        pnl_sinh_vien.add(cmbtn_add_sv, new org.netbeans.lib.awtextra.AbsoluteConstraints(1183, 24, -1, 40));
        cmbtn_add_sv.set_bgColor(new Color(0, 154, 249));

        ccbb_SVchon_nganh.setEditable(false);
        ccbb_SVchon_nganh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "(All) Chọn ngành", "Ngành A", "Ngành B", "Ngành C", "Ngành D", "Ngành E", "Ngành F", "Ngành G", "Ngành H", "Ngành J", "Ngành K" }));
        ccbb_SVchon_nganh.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ccbb_SVchon_nganh.setMaximumSize(new java.awt.Dimension(180, 40));
        ccbb_SVchon_nganh.setMinimumSize(new java.awt.Dimension(180, 40));
        ccbb_SVchon_nganh.setPreferredSize(new java.awt.Dimension(180, 40));
        pnl_sinh_vien.add(ccbb_SVchon_nganh, new org.netbeans.lib.awtextra.AbsoluteConstraints(744, 28, -1, -1));

        ccbb_SVchon_xep_hang.setEditable(false);
        ccbb_SVchon_xep_hang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "(All) Chọn xếp hạng", "Xuất sắc", "Giỏi ", "Khá", "Trung bình", "Trung bình yếu", "Kém" }));
        ccbb_SVchon_xep_hang.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ccbb_SVchon_xep_hang.setMaximumSize(new java.awt.Dimension(180, 40));
        ccbb_SVchon_xep_hang.setMinimumSize(new java.awt.Dimension(180, 40));
        ccbb_SVchon_xep_hang.setPreferredSize(new java.awt.Dimension(180, 40));
        pnl_sinh_vien.add(ccbb_SVchon_xep_hang, new org.netbeans.lib.awtextra.AbsoluteConstraints(1183, 83, -1, -1));

        ccbb_SVchon_lop.setEditable(false);
        ccbb_SVchon_lop.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "(All) Chọn lớp", "Lớp A", "Lớp B", "Lớp C", "Lớp D", "Lớp E", "Lớp F", "Lớp G", "Lớp H", "Lớp K", "Lớp J" }));
        ccbb_SVchon_lop.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ccbb_SVchon_lop.setMaximumSize(new java.awt.Dimension(180, 40));
        ccbb_SVchon_lop.setMinimumSize(new java.awt.Dimension(180, 40));
        ccbb_SVchon_lop.setPreferredSize(new java.awt.Dimension(180, 40));
        pnl_sinh_vien.add(ccbb_SVchon_lop, new org.netbeans.lib.awtextra.AbsoluteConstraints(964, 28, -1, -1));

        ccbb_SV_chon_gioi_tinh.setEditable(false);
        ccbb_SV_chon_gioi_tinh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "(All) Chọn giới tính", "Nam ", "Nữ", "Khác" }));
        ccbb_SV_chon_gioi_tinh.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ccbb_SV_chon_gioi_tinh.setMaximumSize(new java.awt.Dimension(180, 40));
        ccbb_SV_chon_gioi_tinh.setMinimumSize(new java.awt.Dimension(180, 40));
        ccbb_SV_chon_gioi_tinh.setPreferredSize(new java.awt.Dimension(180, 40));
        pnl_sinh_vien.add(ccbb_SV_chon_gioi_tinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(964, 83, -1, -1));

        spnl_sv.setBackground(new java.awt.Color(255, 255, 255));
        spnl_sv.setMaximumSize(new java.awt.Dimension(1275, 612));
        spnl_sv.setMinimumSize(new java.awt.Dimension(1275, 612));
        spnl_sv.setPreferredSize(new java.awt.Dimension(1275, 612));
        spnl_sv.setRowHeaderView(null);
        spnl_sv.setViewportView(ctb_sv);

        ctb_sv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "#", "Mã sinh viên", "Họ và tên", "Ngày sinh", "Giới tính ", "Xếp hạng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ctb_sv.setToolTipText("");
        ctb_sv.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        ctb_sv.setMinimumSize(new java.awt.Dimension(75, 0));
        spnl_sv.setViewportView(ctb_sv);
        if (ctb_sv.getColumnModel().getColumnCount() > 0) {
            ctb_sv.getColumnModel().getColumn(1).setPreferredWidth(250);
            ctb_sv.getColumnModel().getColumn(2).setPreferredWidth(300);
            ctb_sv.getColumnModel().getColumn(3).setPreferredWidth(250);
            ctb_sv.getColumnModel().getColumn(4).setPreferredWidth(200);
            ctb_sv.getColumnModel().getColumn(5).setPreferredWidth(200);
        }
        JPopupMenu popupMenu = new JPopupMenu();
        UIManager.put("JPopupMenu.consumeEventOnClose", Boolean.FALSE);
        ctb_sv.getTableHeader().setComponentPopupMenu(popupMenu);

        pnl_sinh_vien.add(spnl_sv, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 148, -1, -1));
        //spnl_sv.setBorder(null);
        spnl_sv.setVerticalScrollBar(new Custom_scrollBar(5, Color.decode("#3DB5FF"), 1f));
        spnl_sv.getVerticalScrollBar().setOpaque(true);
        spnl_sv.getVerticalScrollBar().setBackground(Color.decode("#C3C3C3"));
        spnl_sv.setCorner(JScrollPane.UPPER_RIGHT_CORNER, new JPanel(){
            @Override
            public void setBackground(Color bg) {
                super.setBackground(Color.decode("#FF8A00")); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
            }
        });

        tbpnl_main.addTab("sinh_vien", pnl_sinh_vien);

        pnl_lop.setBackground(new java.awt.Color(0, 0, 51));
        pnl_lop.setMaximumSize(new java.awt.Dimension(1400, 780));
        pnl_lop.setMinimumSize(new java.awt.Dimension(1400, 780));
        pnl_lop.setPreferredSize(new java.awt.Dimension(1400, 780));
        pnl_lop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbtn_chi_tiet_lop.setForeground(new java.awt.Color(255, 255, 255));
        cmbtn_chi_tiet_lop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Information.png"))); // NOI18N
        cmbtn_chi_tiet_lop.setText("Chi tiết");
        cmbtn_chi_tiet_lop.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbtn_chi_tiet_lop.setIconTextGap(24);
        cmbtn_chi_tiet_lop.setMaximumSize(new java.awt.Dimension(130, 40));
        cmbtn_chi_tiet_lop.setMinimumSize(new java.awt.Dimension(130, 40));
        cmbtn_chi_tiet_lop.setPreferredSize(new java.awt.Dimension(130, 40));
        cmbtn_chi_tiet_lop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbtn_chi_tiet_lopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbtn_chi_tiet_lopMouseExited(evt);
            }
        });
        pnl_lop.add(cmbtn_chi_tiet_lop, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 83, -1, 40));
        cmbtn_chi_tiet_lop.set_bgColor(new Color(0, 154, 249));

        cmbtn_xoa_lop.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cmbtn_xoa_lop.setForeground(new java.awt.Color(255, 255, 255));
        cmbtn_xoa_lop.setText("Xóa lớp học");
        cmbtn_xoa_lop.setToolTipText("");
        cmbtn_xoa_lop.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbtn_xoa_lop.setIconTextGap(24);
        cmbtn_xoa_lop.setMaximumSize(new java.awt.Dimension(130, 40));
        cmbtn_xoa_lop.setMinimumSize(new java.awt.Dimension(130, 40));
        cmbtn_xoa_lop.setPreferredSize(new java.awt.Dimension(130, 40));
        cmbtn_xoa_lop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbtn_xoa_lopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbtn_xoa_lopMouseExited(evt);
            }
        });
        pnl_lop.add(cmbtn_xoa_lop, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 83, -1, 40));
        cmbtn_xoa_lop.set_bgColor(new Color(249, 0, 0));

        cmbtn_add_lop.setForeground(new java.awt.Color(255, 255, 255));
        cmbtn_add_lop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add circle.png"))); // NOI18N
        cmbtn_add_lop.setText("Thêm lớp học");
        cmbtn_add_lop.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbtn_add_lop.setIconTextGap(24);
        cmbtn_add_lop.setMaximumSize(new java.awt.Dimension(180, 40));
        cmbtn_add_lop.setMinimumSize(new java.awt.Dimension(180, 40));
        cmbtn_add_lop.setPreferredSize(new java.awt.Dimension(180, 40));
        cmbtn_add_lop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbtn_add_lopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbtn_add_lopMouseExited(evt);
            }
        });
        cmbtn_add_lop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtn_add_lopActionPerformed(evt);
            }
        });
        pnl_lop.add(cmbtn_add_lop, new org.netbeans.lib.awtextra.AbsoluteConstraints(1183, 24, -1, 40));
        cmbtn_add_lop.set_bgColor(new Color(0, 154, 249));

        ccbb_Lop_chon_nganh.setEditable(false);
        ccbb_Lop_chon_nganh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "(All) Chọn ngành", "Ngành A", "Ngành B", "Ngành C", "Ngành D", "Ngành E", "Ngành F", "Ngành G", "Ngành H", "Ngành J", "Ngành K" }));
        ccbb_Lop_chon_nganh.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ccbb_Lop_chon_nganh.setMaximumSize(new java.awt.Dimension(180, 40));
        ccbb_Lop_chon_nganh.setMinimumSize(new java.awt.Dimension(180, 40));
        ccbb_Lop_chon_nganh.setPreferredSize(new java.awt.Dimension(180, 40));
        pnl_lop.add(ccbb_Lop_chon_nganh, new org.netbeans.lib.awtextra.AbsoluteConstraints(965, 28, -1, -1));

        spnl_lop.setMaximumSize(new java.awt.Dimension(1275, 612));
        spnl_lop.setMinimumSize(new java.awt.Dimension(1275, 612));
        spnl_lop.setPreferredSize(new java.awt.Dimension(1275, 612));

        ctb_lop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "#", "Mã lớp học", "Tên lớp học", "Giáo viên phụ trách", "Số lượng sinh viên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ctb_lop.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        spnl_lop.setViewportView(ctb_lop);
        if (ctb_lop.getColumnModel().getColumnCount() > 0) {
            ctb_lop.getColumnModel().getColumn(0).setPreferredWidth(75);
            ctb_lop.getColumnModel().getColumn(1).setPreferredWidth(300);
            ctb_lop.getColumnModel().getColumn(2).setPreferredWidth(350);
            ctb_lop.getColumnModel().getColumn(3).setPreferredWidth(350);
            ctb_lop.getColumnModel().getColumn(4).setPreferredWidth(200);
        }

        pnl_lop.add(spnl_lop, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 148, -1, -1));
        spnl_lop.setVerticalScrollBar(new Custom_scrollBar(5, Color.decode("#3DB5FF"), 1f));
        spnl_lop.getVerticalScrollBar().setOpaque(true);
        spnl_lop.getVerticalScrollBar().setBackground(Color.decode("#C3C3C3"));
        spnl_lop.setCorner(JScrollPane.UPPER_RIGHT_CORNER, new JPanel(){
            @Override
            public void setBackground(Color bg) {
                super.setBackground(Color.decode("#FF8A00")); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
            }
        });

        tbpnl_main.addTab("lop", pnl_lop);

        pnl_nganh_hoc.setBackground(new java.awt.Color(0, 0, 51));
        pnl_nganh_hoc.setMaximumSize(new java.awt.Dimension(1400, 780));
        pnl_nganh_hoc.setMinimumSize(new java.awt.Dimension(1400, 780));
        pnl_nganh_hoc.setPreferredSize(new java.awt.Dimension(1400, 780));
        pnl_nganh_hoc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbtn_chi_tiet_nganh_hoc.setForeground(new java.awt.Color(255, 255, 255));
        cmbtn_chi_tiet_nganh_hoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Information.png"))); // NOI18N
        cmbtn_chi_tiet_nganh_hoc.setText("Chi tiết");
        cmbtn_chi_tiet_nganh_hoc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbtn_chi_tiet_nganh_hoc.setIconTextGap(24);
        cmbtn_chi_tiet_nganh_hoc.setMaximumSize(new java.awt.Dimension(130, 40));
        cmbtn_chi_tiet_nganh_hoc.setMinimumSize(new java.awt.Dimension(130, 40));
        cmbtn_chi_tiet_nganh_hoc.setPreferredSize(new java.awt.Dimension(130, 40));
        cmbtn_chi_tiet_nganh_hoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbtn_chi_tiet_nganh_hocMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbtn_chi_tiet_nganh_hocMouseExited(evt);
            }
        });
        pnl_nganh_hoc.add(cmbtn_chi_tiet_nganh_hoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 83, -1, 40));
        cmbtn_chi_tiet_nganh_hoc.set_bgColor(new Color(0, 154, 249));

        cmbtn_xoa_nganh_hoc.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cmbtn_xoa_nganh_hoc.setForeground(new java.awt.Color(255, 255, 255));
        cmbtn_xoa_nganh_hoc.setText("Xóa ngành học");
        cmbtn_xoa_nganh_hoc.setToolTipText("");
        cmbtn_xoa_nganh_hoc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbtn_xoa_nganh_hoc.setIconTextGap(24);
        cmbtn_xoa_nganh_hoc.setMaximumSize(new java.awt.Dimension(130, 40));
        cmbtn_xoa_nganh_hoc.setMinimumSize(new java.awt.Dimension(130, 40));
        cmbtn_xoa_nganh_hoc.setPreferredSize(new java.awt.Dimension(130, 40));
        cmbtn_xoa_nganh_hoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbtn_xoa_nganh_hocMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbtn_xoa_nganh_hocMouseExited(evt);
            }
        });
        pnl_nganh_hoc.add(cmbtn_xoa_nganh_hoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 83, -1, 40));
        cmbtn_xoa_nganh_hoc.set_bgColor(new Color(249, 0, 0));

        cmbtn_add_nganh_hoc.setForeground(new java.awt.Color(255, 255, 255));
        cmbtn_add_nganh_hoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add circle.png"))); // NOI18N
        cmbtn_add_nganh_hoc.setText("Thêm ngành học");
        cmbtn_add_nganh_hoc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbtn_add_nganh_hoc.setIconTextGap(24);
        cmbtn_add_nganh_hoc.setMaximumSize(new java.awt.Dimension(180, 40));
        cmbtn_add_nganh_hoc.setMinimumSize(new java.awt.Dimension(180, 40));
        cmbtn_add_nganh_hoc.setPreferredSize(new java.awt.Dimension(180, 40));
        cmbtn_add_nganh_hoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbtn_add_nganh_hocMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbtn_add_nganh_hocMouseExited(evt);
            }
        });
        cmbtn_add_nganh_hoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtn_add_nganh_hocActionPerformed(evt);
            }
        });
        pnl_nganh_hoc.add(cmbtn_add_nganh_hoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1183, 24, -1, 40));
        cmbtn_add_nganh_hoc.set_bgColor(new Color(0, 154, 249));

        spnl_nganh.setMaximumSize(new java.awt.Dimension(1275, 612));
        spnl_nganh.setMinimumSize(new java.awt.Dimension(1275, 612));
        spnl_nganh.setPreferredSize(new java.awt.Dimension(1275, 612));

        ctb_nganh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "#", "Mã ngành học", "Tên ngành học", "Số môn học"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ctb_nganh.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        spnl_nganh.setViewportView(ctb_nganh);
        if (ctb_nganh.getColumnModel().getColumnCount() > 0) {
            ctb_nganh.getColumnModel().getColumn(0).setPreferredWidth(75);
            ctb_nganh.getColumnModel().getColumn(1).setPreferredWidth(400);
            ctb_nganh.getColumnModel().getColumn(2).setPreferredWidth(400);
            ctb_nganh.getColumnModel().getColumn(3).setMinWidth(350);
            ctb_nganh.getColumnModel().getColumn(3).setPreferredWidth(400);
            ctb_nganh.getColumnModel().getColumn(3).setMaxWidth(350);
        }

        pnl_nganh_hoc.add(spnl_nganh, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 148, -1, -1));
        spnl_nganh.setVerticalScrollBar(new Custom_scrollBar(5, Color.decode("#3DB5FF"), 1f));
        spnl_nganh.getVerticalScrollBar().setOpaque(true);
        spnl_nganh.getVerticalScrollBar().setBackground(Color.decode("#C3C3C3"));
        spnl_nganh.setCorner(JScrollPane.UPPER_RIGHT_CORNER, new JPanel(){
            @Override
            public void setBackground(Color bg) {
                super.setBackground(Color.decode("#FF8A00")); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
            }
        });

        tbpnl_main.addTab("nganh_hoc", pnl_nganh_hoc);

        pnl_giao_vien.setBackground(new java.awt.Color(0, 0, 51));
        pnl_giao_vien.setMaximumSize(new java.awt.Dimension(1400, 780));
        pnl_giao_vien.setMinimumSize(new java.awt.Dimension(1400, 780));
        pnl_giao_vien.setPreferredSize(new java.awt.Dimension(1400, 780));
        pnl_giao_vien.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbtn_chi_tiet_GV.setForeground(new java.awt.Color(255, 255, 255));
        cmbtn_chi_tiet_GV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Information.png"))); // NOI18N
        cmbtn_chi_tiet_GV.setText("Chi tiết");
        cmbtn_chi_tiet_GV.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbtn_chi_tiet_GV.setIconTextGap(24);
        cmbtn_chi_tiet_GV.setMaximumSize(new java.awt.Dimension(130, 40));
        cmbtn_chi_tiet_GV.setMinimumSize(new java.awt.Dimension(130, 40));
        cmbtn_chi_tiet_GV.setPreferredSize(new java.awt.Dimension(130, 40));
        cmbtn_chi_tiet_GV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbtn_chi_tiet_GVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbtn_chi_tiet_GVMouseExited(evt);
            }
        });
        pnl_giao_vien.add(cmbtn_chi_tiet_GV, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 83, -1, 40));
        cmbtn_chi_tiet_GV.set_bgColor(new Color(0, 154, 249));

        cmbtn_xoa_GV.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cmbtn_xoa_GV.setForeground(new java.awt.Color(255, 255, 255));
        cmbtn_xoa_GV.setText("Xóa giáo viên");
        cmbtn_xoa_GV.setToolTipText("");
        cmbtn_xoa_GV.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbtn_xoa_GV.setIconTextGap(24);
        cmbtn_xoa_GV.setMaximumSize(new java.awt.Dimension(130, 40));
        cmbtn_xoa_GV.setMinimumSize(new java.awt.Dimension(130, 40));
        cmbtn_xoa_GV.setPreferredSize(new java.awt.Dimension(130, 40));
        cmbtn_xoa_GV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbtn_xoa_GVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbtn_xoa_GVMouseExited(evt);
            }
        });
        pnl_giao_vien.add(cmbtn_xoa_GV, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 83, -1, 40));
        cmbtn_xoa_GV.set_bgColor(new Color(249, 0, 0));

        ccbb_chon_gioi_tinh_GV.setEditable(false);
        ccbb_chon_gioi_tinh_GV.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "(All) Chọn giới tính", "Nam ", "Nữ", "Khác" }));
        ccbb_chon_gioi_tinh_GV.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ccbb_chon_gioi_tinh_GV.setMaximumSize(new java.awt.Dimension(180, 40));
        ccbb_chon_gioi_tinh_GV.setMinimumSize(new java.awt.Dimension(180, 40));
        ccbb_chon_gioi_tinh_GV.setPreferredSize(new java.awt.Dimension(180, 40));
        pnl_giao_vien.add(ccbb_chon_gioi_tinh_GV, new org.netbeans.lib.awtextra.AbsoluteConstraints(1183, 83, -1, -1));

        cmbtn_sx_GV.setForeground(new java.awt.Color(255, 255, 255));
        cmbtn_sx_GV.setText("Sắp xếp tên");
        cmbtn_sx_GV.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbtn_sx_GV.setIconTextGap(24);
        cmbtn_sx_GV.setMaximumSize(new java.awt.Dimension(180, 40));
        cmbtn_sx_GV.setMinimumSize(new java.awt.Dimension(180, 40));
        cmbtn_sx_GV.setPreferredSize(new java.awt.Dimension(180, 40));
        cmbtn_sx_GV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbtn_sx_GVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbtn_sx_GVMouseExited(evt);
            }
        });
        cmbtn_sx_GV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtn_sx_GVActionPerformed(evt);
            }
        });
        pnl_giao_vien.add(cmbtn_sx_GV, new org.netbeans.lib.awtextra.AbsoluteConstraints(964, 83, -1, 40));
        cmbtn_sx_GV.set_bgColor(new Color(0, 154, 249));

        cmbtn_add_GV.setForeground(new java.awt.Color(255, 255, 255));
        cmbtn_add_GV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add.png"))); // NOI18N
        cmbtn_add_GV.setText("Thêm giáo viên");
        cmbtn_add_GV.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbtn_add_GV.setIconTextGap(24);
        cmbtn_add_GV.setMaximumSize(new java.awt.Dimension(180, 40));
        cmbtn_add_GV.setMinimumSize(new java.awt.Dimension(180, 40));
        cmbtn_add_GV.setPreferredSize(new java.awt.Dimension(180, 40));
        cmbtn_add_GV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbtn_add_GVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbtn_add_GVMouseExited(evt);
            }
        });
        cmbtn_add_GV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtn_add_GVActionPerformed(evt);
            }
        });
        pnl_giao_vien.add(cmbtn_add_GV, new org.netbeans.lib.awtextra.AbsoluteConstraints(1183, 24, -1, 40));
        cmbtn_add_GV.set_bgColor(new Color(0, 154, 249));

        spnl_GV.setMaximumSize(new java.awt.Dimension(1275, 612));
        spnl_GV.setMinimumSize(new java.awt.Dimension(1275, 612));
        spnl_GV.setPreferredSize(new java.awt.Dimension(1275, 612));

        ctb_GV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "#", "Mã giáo viên", "Họ và tên", "Số môn học", "Giới tính"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ctb_GV.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        spnl_GV.setViewportView(ctb_GV);
        if (ctb_GV.getColumnModel().getColumnCount() > 0) {
            ctb_GV.getColumnModel().getColumn(0).setPreferredWidth(75);
            ctb_GV.getColumnModel().getColumn(1).setPreferredWidth(400);
            ctb_GV.getColumnModel().getColumn(2).setPreferredWidth(400);
            ctb_GV.getColumnModel().getColumn(3).setMinWidth(350);
            ctb_GV.getColumnModel().getColumn(3).setPreferredWidth(400);
            ctb_GV.getColumnModel().getColumn(3).setMaxWidth(350);
            ctb_GV.getColumnModel().getColumn(4).setMinWidth(250);
            ctb_GV.getColumnModel().getColumn(4).setPreferredWidth(250);
            ctb_GV.getColumnModel().getColumn(4).setMaxWidth(250);
        }

        pnl_giao_vien.add(spnl_GV, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 148, -1, -1));
        spnl_GV.setVerticalScrollBar(new Custom_scrollBar(5, Color.decode("#3DB5FF"), 1f));
        spnl_GV.getVerticalScrollBar().setOpaque(true);
        spnl_GV.getVerticalScrollBar().setBackground(Color.decode("#C3C3C3"));
        spnl_GV.setCorner(JScrollPane.UPPER_RIGHT_CORNER, new JPanel(){
            @Override
            public void setBackground(Color bg) {
                super.setBackground(Color.decode("#FF8A00")); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
            }
        });

        tbpnl_main.addTab("giao_vien", pnl_giao_vien);

        pnl_mon_hoc.setBackground(new java.awt.Color(0, 0, 51));
        pnl_mon_hoc.setMaximumSize(new java.awt.Dimension(1400, 780));
        pnl_mon_hoc.setMinimumSize(new java.awt.Dimension(1400, 780));
        pnl_mon_hoc.setPreferredSize(new java.awt.Dimension(1400, 780));
        pnl_mon_hoc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbtn_chi_tiet_mon_hoc.setForeground(new java.awt.Color(255, 255, 255));
        cmbtn_chi_tiet_mon_hoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Information.png"))); // NOI18N
        cmbtn_chi_tiet_mon_hoc.setText("Chi tiết");
        cmbtn_chi_tiet_mon_hoc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbtn_chi_tiet_mon_hoc.setIconTextGap(24);
        cmbtn_chi_tiet_mon_hoc.setMaximumSize(new java.awt.Dimension(130, 40));
        cmbtn_chi_tiet_mon_hoc.setMinimumSize(new java.awt.Dimension(130, 40));
        cmbtn_chi_tiet_mon_hoc.setPreferredSize(new java.awt.Dimension(130, 40));
        cmbtn_chi_tiet_mon_hoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbtn_chi_tiet_mon_hocMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbtn_chi_tiet_mon_hocMouseExited(evt);
            }
        });
        pnl_mon_hoc.add(cmbtn_chi_tiet_mon_hoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 83, -1, 40));
        cmbtn_chi_tiet_mon_hoc.set_bgColor(new Color(0, 154, 249));

        cmbtn_xoa_mon_hoc.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        cmbtn_xoa_mon_hoc.setForeground(new java.awt.Color(255, 255, 255));
        cmbtn_xoa_mon_hoc.setText("Xóa môn học");
        cmbtn_xoa_mon_hoc.setToolTipText("");
        cmbtn_xoa_mon_hoc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbtn_xoa_mon_hoc.setIconTextGap(24);
        cmbtn_xoa_mon_hoc.setMaximumSize(new java.awt.Dimension(130, 40));
        cmbtn_xoa_mon_hoc.setMinimumSize(new java.awt.Dimension(130, 40));
        cmbtn_xoa_mon_hoc.setPreferredSize(new java.awt.Dimension(130, 40));
        cmbtn_xoa_mon_hoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbtn_xoa_mon_hocMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbtn_xoa_mon_hocMouseExited(evt);
            }
        });
        pnl_mon_hoc.add(cmbtn_xoa_mon_hoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 83, -1, 40));
        cmbtn_xoa_mon_hoc.set_bgColor(new Color(249, 0, 0));

        cmbtn_add_mon_hoc.setForeground(new java.awt.Color(255, 255, 255));
        cmbtn_add_mon_hoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/add circle.png"))); // NOI18N
        cmbtn_add_mon_hoc.setText("Thêm môn học");
        cmbtn_add_mon_hoc.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cmbtn_add_mon_hoc.setIconTextGap(24);
        cmbtn_add_mon_hoc.setMaximumSize(new java.awt.Dimension(180, 40));
        cmbtn_add_mon_hoc.setMinimumSize(new java.awt.Dimension(180, 40));
        cmbtn_add_mon_hoc.setPreferredSize(new java.awt.Dimension(180, 40));
        cmbtn_add_mon_hoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbtn_add_mon_hocMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbtn_add_mon_hocMouseExited(evt);
            }
        });
        cmbtn_add_mon_hoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtn_add_mon_hocActionPerformed(evt);
            }
        });
        pnl_mon_hoc.add(cmbtn_add_mon_hoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1183, 24, -1, 40));
        cmbtn_add_mon_hoc.set_bgColor(new Color(0, 154, 249));

        spnl_mon_hoc.setMaximumSize(new java.awt.Dimension(1275, 612));
        spnl_mon_hoc.setMinimumSize(new java.awt.Dimension(1275, 612));
        spnl_mon_hoc.setPreferredSize(new java.awt.Dimension(1275, 612));

        custom_tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "#", "Mã môn học", "Tên môn học"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spnl_mon_hoc.setViewportView(custom_tb1);
        if (custom_tb1.getColumnModel().getColumnCount() > 0) {
            custom_tb1.getColumnModel().getColumn(0).setPreferredWidth(75);
            custom_tb1.getColumnModel().getColumn(1).setPreferredWidth(400);
            custom_tb1.getColumnModel().getColumn(2).setPreferredWidth(800);
        }

        pnl_mon_hoc.add(spnl_mon_hoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 148, -1, -1));
        spnl_mon_hoc.setVerticalScrollBar(new Custom_scrollBar(5, Color.decode("#3DB5FF"), 1f));
        spnl_mon_hoc.getVerticalScrollBar().setOpaque(true);
        spnl_mon_hoc.getVerticalScrollBar().setBackground(Color.decode("#C3C3C3"));
        spnl_mon_hoc.setCorner(JScrollPane.UPPER_RIGHT_CORNER, new JPanel(){
            @Override
            public void setBackground(Color bg) {
                super.setBackground(Color.decode("#FF8A00")); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
            }
        });

        tbpnl_main.addTab("mon_hoc", pnl_mon_hoc);

        tbpnl_main.setSelectedIndex(2);

        pnl_content.add(tbpnl_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -35, -1, 815));

        pnl_main.add(pnl_content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbtn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbtn_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_cbtn_closeMouseClicked

    private void cbtn_closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbtn_closeMouseEntered
        cbtn_close.set_bgColor(new Color(255, 80, 80));
    }//GEN-LAST:event_cbtn_closeMouseEntered

    private void cbtn_closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbtn_closeMouseExited
        cbtn_close.set_bgColor(Color.WHITE);
    }//GEN-LAST:event_cbtn_closeMouseExited

    private void cbtn_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbtn_minimizeMouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_cbtn_minimizeMouseClicked

    private void cbtn_minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbtn_minimizeMouseEntered
        cbtn_minimize.set_bgColor(new Color(243, 243, 243));
    }//GEN-LAST:event_cbtn_minimizeMouseEntered

    private void cbtn_minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbtn_minimizeMouseExited
        cbtn_minimize.set_bgColor(Color.WHITE);
    }//GEN-LAST:event_cbtn_minimizeMouseExited

    private void cmbtn_trang_chuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_trang_chuMouseEntered
        cmbtn_trang_chu.set_bgColor(new Color(72, 72, 72));
    }//GEN-LAST:event_cmbtn_trang_chuMouseEntered

    private void cmbtn_trang_chuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_trang_chuMouseExited
        if (menuSelected != 0) {
            cmbtn_trang_chu.set_bgColor(new Color(26, 24, 24));
        }
    }//GEN-LAST:event_cmbtn_trang_chuMouseExited

    private void cmbtn_trang_chuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_trang_chuMouseClicked
        try {
            resetBg_menuButton();
        } catch (InterruptedException ex) {
            Logger.getLogger(Verwalten.class.getName()).log(Level.SEVERE, null, ex);
        }
        cmbtn_trang_chu.set_bgColor(new Color(72, 72, 72));
        tbpnl_main.setSelectedIndex(0);
        menuSelected = 0;
    }//GEN-LAST:event_cmbtn_trang_chuMouseClicked

    private void cmbtn_sinh_vienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_sinh_vienMouseClicked

        try {
            resetBg_menuButton();
        } catch (InterruptedException ex) {
            Logger.getLogger(Verwalten.class.getName()).log(Level.SEVERE, null, ex);
        }
        cmbtn_sinh_vien.set_bgColor(new Color(72, 72, 72));
        tbpnl_main.setSelectedIndex(1);
        menuSelected = 1;
    }//GEN-LAST:event_cmbtn_sinh_vienMouseClicked

    private void cmbtn_sinh_vienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_sinh_vienMouseEntered
        cmbtn_sinh_vien.set_bgColor(new Color(72, 72, 72));
    }//GEN-LAST:event_cmbtn_sinh_vienMouseEntered

    private void cmbtn_sinh_vienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_sinh_vienMouseExited
        if (menuSelected != 1) {
            cmbtn_sinh_vien.set_bgColor(new Color(26, 24, 24));
        }
    }//GEN-LAST:event_cmbtn_sinh_vienMouseExited

    private void cmbtn_lopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_lopMouseClicked
        try {
            resetBg_menuButton();
        } catch (InterruptedException ex) {
            Logger.getLogger(Verwalten.class.getName()).log(Level.SEVERE, null, ex);
        }
        cmbtn_lop.set_bgColor(new Color(72, 72, 72));
        tbpnl_main.setSelectedIndex(2);
        menuSelected = 2;
    }//GEN-LAST:event_cmbtn_lopMouseClicked

    private void cmbtn_lopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_lopMouseEntered
        cmbtn_lop.set_bgColor(new Color(72, 72, 72));
    }//GEN-LAST:event_cmbtn_lopMouseEntered

    private void cmbtn_nganhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_nganhMouseClicked
        try {
            resetBg_menuButton();
        } catch (InterruptedException ex) {
            Logger.getLogger(Verwalten.class.getName()).log(Level.SEVERE, null, ex);
        }
        cmbtn_nganh.set_bgColor(new Color(72, 72, 72));
        tbpnl_main.setSelectedIndex(3);
        menuSelected = 3;
    }//GEN-LAST:event_cmbtn_nganhMouseClicked

    private void cmbtn_giao_vienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_giao_vienMouseClicked
        try {
            resetBg_menuButton();
        } catch (InterruptedException ex) {
            Logger.getLogger(Verwalten.class.getName()).log(Level.SEVERE, null, ex);
        }
        cmbtn_giao_vien.set_bgColor(new Color(72, 72, 72));
        tbpnl_main.setSelectedIndex(4);
        menuSelected = 4;
    }//GEN-LAST:event_cmbtn_giao_vienMouseClicked

    private void cmbtn_monMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_monMouseClicked
        try {
            resetBg_menuButton();
        } catch (InterruptedException ex) {
            Logger.getLogger(Verwalten.class.getName()).log(Level.SEVERE, null, ex);
        }
        cmbtn_mon.set_bgColor(new Color(72, 72, 72));
        tbpnl_main.setSelectedIndex(5);
        menuSelected = 5;
    }//GEN-LAST:event_cmbtn_monMouseClicked

    private void cmbtn_lopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_lopMouseExited
        if (menuSelected != 2) {
            cmbtn_lop.set_bgColor(new Color(26, 24, 24));
        }
    }//GEN-LAST:event_cmbtn_lopMouseExited

    private void cmbtn_nganhMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_nganhMouseEntered
        cmbtn_nganh.set_bgColor(new Color(72, 72, 72));
    }//GEN-LAST:event_cmbtn_nganhMouseEntered

    private void cmbtn_nganhMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_nganhMouseExited
        if (menuSelected != 3) {
            cmbtn_nganh.set_bgColor(new Color(26, 24, 24));
        }
    }//GEN-LAST:event_cmbtn_nganhMouseExited

    private void cmbtn_giao_vienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_giao_vienMouseEntered
        cmbtn_giao_vien.set_bgColor(new Color(72, 72, 72));
    }//GEN-LAST:event_cmbtn_giao_vienMouseEntered

    private void cmbtn_monMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_monMouseEntered
        cmbtn_mon.set_bgColor(new Color(72, 72, 72));
    }//GEN-LAST:event_cmbtn_monMouseEntered

    private void cmbtn_giao_vienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_giao_vienMouseExited
        if (menuSelected != 4) {
            cmbtn_giao_vien.set_bgColor(new Color(26, 24, 24));
        }
    }//GEN-LAST:event_cmbtn_giao_vienMouseExited

    private void cmbtn_monMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_monMouseExited
        if (menuSelected != 5) {
            cmbtn_mon.set_bgColor(new Color(26, 24, 24));
        }
    }//GEN-LAST:event_cmbtn_monMouseExited

    private void cmbtn_menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_menuMouseEntered
        cmbtn_menu.set_bgColor(new Color(72, 72, 72));
    }//GEN-LAST:event_cmbtn_menuMouseEntered

    private void cmbtn_menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_menuMouseExited
        cmbtn_menu.set_bgColor(new Color(26, 24, 24));
    }//GEN-LAST:event_cmbtn_menuMouseExited

    private void cmbtn_menu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_menu1MouseEntered
        cmbtn_menu1.set_bgColor(new Color(72, 72, 72));
    }//GEN-LAST:event_cmbtn_menu1MouseEntered

    private void cmbtn_menu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_menu1MouseExited
        cmbtn_menu1.set_bgColor(new Color(26, 24, 24));
    }//GEN-LAST:event_cmbtn_menu1MouseExited

    private void cmbtn_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_menuMouseClicked
        state_Menu();
    }//GEN-LAST:event_cmbtn_menuMouseClicked

    private void cmbtn_menu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_menu1MouseClicked
        state_Menu();
    }//GEN-LAST:event_cmbtn_menu1MouseClicked

    private void lbl_sinh_vienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_sinh_vienMouseClicked
        try {
            resetBg_menuButton();
        } catch (InterruptedException ex) {
            Logger.getLogger(Verwalten.class.getName()).log(Level.SEVERE, null, ex);
        }
        menuSelected = 1;
        cmbtn_sinh_vien.set_bgColor(new Color(72, 72, 72));
        tbpnl_main.setSelectedIndex(menuSelected);
    }//GEN-LAST:event_lbl_sinh_vienMouseClicked

    private void lbl_lop_hocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_lop_hocMouseClicked
        try {
            resetBg_menuButton();
        } catch (InterruptedException ex) {
            Logger.getLogger(Verwalten.class.getName()).log(Level.SEVERE, null, ex);
        }
        menuSelected = 2;
        cmbtn_lop.set_bgColor(new Color(72, 72, 72));
        tbpnl_main.setSelectedIndex(menuSelected);
        
    }//GEN-LAST:event_lbl_lop_hocMouseClicked

    private void lbl_nganh_hocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_nganh_hocMouseClicked
        try {
            resetBg_menuButton();
        } catch (InterruptedException ex) {
            Logger.getLogger(Verwalten.class.getName()).log(Level.SEVERE, null, ex);
        }
        menuSelected = 3;
        cmbtn_nganh.set_bgColor(new Color(72, 72, 72));
        tbpnl_main.setSelectedIndex(menuSelected);
    }//GEN-LAST:event_lbl_nganh_hocMouseClicked

    private void lbl_giao_vienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_giao_vienMouseClicked
        try {
            resetBg_menuButton();
        } catch (InterruptedException ex) {
            Logger.getLogger(Verwalten.class.getName()).log(Level.SEVERE, null, ex);
        }
        menuSelected = 4;
        cmbtn_giao_vien.set_bgColor(new Color(72, 72, 72));
        tbpnl_main.setSelectedIndex(menuSelected);
    }//GEN-LAST:event_lbl_giao_vienMouseClicked

    private void lbl_mon_hocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_mon_hocMouseClicked
        try {
            resetBg_menuButton();
        } catch (InterruptedException ex) {
            Logger.getLogger(Verwalten.class.getName()).log(Level.SEVERE, null, ex);
        }
        menuSelected = 5;
        cmbtn_mon.set_bgColor(new Color(72, 72, 72));
        tbpnl_main.setSelectedIndex(menuSelected);
    }//GEN-LAST:event_lbl_mon_hocMouseClicked

    private void cmbtn_sx_svActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtn_sx_svActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtn_sx_svActionPerformed

    private void cmbtn_add_svActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtn_add_svActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtn_add_svActionPerformed

    private void cmbtn_chi_tiet_svMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_chi_tiet_svMouseEntered
        cmbtn_chi_tiet_sv.set_bgColor(new Color(80, 188, 255));
    }//GEN-LAST:event_cmbtn_chi_tiet_svMouseEntered

    private void cmbtn_xoa_svMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_xoa_svMouseEntered
       cmbtn_xoa_sv.set_bgColor(new Color(255, 91, 91));
    }//GEN-LAST:event_cmbtn_xoa_svMouseEntered

    private void cmbtn_sx_svMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_sx_svMouseEntered
        cmbtn_sx_sv.set_bgColor(new Color(80, 188, 255));
    }//GEN-LAST:event_cmbtn_sx_svMouseEntered

    private void cmbtn_add_svMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_add_svMouseEntered
        cmbtn_add_sv.set_bgColor(new Color(80, 188, 255));
    }//GEN-LAST:event_cmbtn_add_svMouseEntered

    private void cmbtn_chi_tiet_svMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_chi_tiet_svMouseExited
        cmbtn_chi_tiet_sv.set_bgColor(new Color(0, 154, 249));
        
    }//GEN-LAST:event_cmbtn_chi_tiet_svMouseExited

    private void cmbtn_sx_svMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_sx_svMouseExited
        cmbtn_sx_sv.set_bgColor(new Color(0, 154, 249));
    }//GEN-LAST:event_cmbtn_sx_svMouseExited

    private void cmbtn_add_svMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_add_svMouseExited
        cmbtn_add_sv.set_bgColor(new Color(0, 154, 249));
    }//GEN-LAST:event_cmbtn_add_svMouseExited

    private void cmbtn_xoa_svMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_xoa_svMouseExited
        cmbtn_xoa_sv.set_bgColor(new Color(249, 0, 0));
    }//GEN-LAST:event_cmbtn_xoa_svMouseExited

    private void cmbtn_chi_tiet_lopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_chi_tiet_lopMouseEntered
        cmbtn_chi_tiet_lop.set_bgColor(new Color(80, 188, 255));
    }//GEN-LAST:event_cmbtn_chi_tiet_lopMouseEntered

    private void cmbtn_chi_tiet_lopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_chi_tiet_lopMouseExited
        cmbtn_chi_tiet_lop.set_bgColor(new Color(0, 154, 249));
    }//GEN-LAST:event_cmbtn_chi_tiet_lopMouseExited

    private void cmbtn_xoa_lopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_xoa_lopMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtn_xoa_lopMouseEntered

    private void cmbtn_xoa_lopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_xoa_lopMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtn_xoa_lopMouseExited

    private void cmbtn_add_lopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_add_lopMouseEntered
        cmbtn_add_lop.set_bgColor(new Color(80, 188, 255));
    }//GEN-LAST:event_cmbtn_add_lopMouseEntered

    private void cmbtn_add_lopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_add_lopMouseExited
        cmbtn_add_lop.set_bgColor(new Color(0, 154, 249));
    }//GEN-LAST:event_cmbtn_add_lopMouseExited

    private void cmbtn_add_lopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtn_add_lopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtn_add_lopActionPerformed

    private void cmbtn_chi_tiet_nganh_hocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_chi_tiet_nganh_hocMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtn_chi_tiet_nganh_hocMouseEntered

    private void cmbtn_chi_tiet_nganh_hocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_chi_tiet_nganh_hocMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtn_chi_tiet_nganh_hocMouseExited

    private void cmbtn_xoa_nganh_hocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_xoa_nganh_hocMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtn_xoa_nganh_hocMouseEntered

    private void cmbtn_xoa_nganh_hocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_xoa_nganh_hocMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtn_xoa_nganh_hocMouseExited

    private void cmbtn_add_nganh_hocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_add_nganh_hocMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtn_add_nganh_hocMouseEntered

    private void cmbtn_add_nganh_hocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_add_nganh_hocMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtn_add_nganh_hocMouseExited

    private void cmbtn_add_nganh_hocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtn_add_nganh_hocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtn_add_nganh_hocActionPerformed

    private void cmbtn_chi_tiet_GVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_chi_tiet_GVMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtn_chi_tiet_GVMouseEntered

    private void cmbtn_chi_tiet_GVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_chi_tiet_GVMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtn_chi_tiet_GVMouseExited

    private void cmbtn_xoa_GVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_xoa_GVMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtn_xoa_GVMouseEntered

    private void cmbtn_xoa_GVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_xoa_GVMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtn_xoa_GVMouseExited

    private void cmbtn_add_GVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_add_GVMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtn_add_GVMouseEntered

    private void cmbtn_add_GVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_add_GVMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtn_add_GVMouseExited

    private void cmbtn_add_GVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtn_add_GVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtn_add_GVActionPerformed

    private void cmbtn_sx_GVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_sx_GVMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtn_sx_GVMouseEntered

    private void cmbtn_sx_GVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_sx_GVMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtn_sx_GVMouseExited

    private void cmbtn_sx_GVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtn_sx_GVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtn_sx_GVActionPerformed

    private void cmbtn_chi_tiet_mon_hocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_chi_tiet_mon_hocMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtn_chi_tiet_mon_hocMouseEntered

    private void cmbtn_chi_tiet_mon_hocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_chi_tiet_mon_hocMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtn_chi_tiet_mon_hocMouseExited

    private void cmbtn_xoa_mon_hocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_xoa_mon_hocMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtn_xoa_mon_hocMouseEntered

    private void cmbtn_xoa_mon_hocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_xoa_mon_hocMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtn_xoa_mon_hocMouseExited

    private void cmbtn_add_mon_hocMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_add_mon_hocMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtn_add_mon_hocMouseEntered

    private void cmbtn_add_mon_hocMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbtn_add_mon_hocMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtn_add_mon_hocMouseExited

    private void cmbtn_add_mon_hocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtn_add_mon_hocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbtn_add_mon_hocActionPerformed

    private void resetBg_menuButton() throws InterruptedException {
        Thread th = new Thread() {
            @Override
            public void run() {
                switch (menuSelected) {
                    case 0 ->
                        cmbtn_trang_chu.set_bgColor(new Color(26, 24, 24));
                    case 1 ->
                        cmbtn_sinh_vien.set_bgColor(new Color(26, 24, 24));
                    case 2 ->
                        cmbtn_lop.set_bgColor(new Color(26, 24, 24));
                    case 3 ->
                        cmbtn_nganh.set_bgColor(new Color(26, 24, 24));
                    case 4 ->
                        cmbtn_giao_vien.set_bgColor(new Color(26, 24, 24));
                    case 5 ->
                        cmbtn_mon.set_bgColor(new Color(26, 24, 24));
                }
                repaint();
            }
        };

        th.start();
        th.join();
    }

    private void state_Menu() {
        if (pnl_menu.getLocation().x == 0) {
            Thread th = new Thread() {
                @Override
                public void run() {
                    for (int i = 0; i >= -236; i--) {
                        pnl_menu.setLocation(i, 0);
                    }
                    menuLoactionX = -236;
                }

            };
            th.start();
            try {
                th.join();
            } catch (InterruptedException ex) {
                Logger.getLogger(Verwalten.class.getName()).log(Level.SEVERE, null, ex);
            }
            th = null;
        } else if (pnl_menu.getLocation().x == -236) {
            Thread th = new Thread() {
                @Override
                public void run() {
                    for (int i = -236; i <= 0; i++) {
                        pnl_menu.setLocation(i, 0);
                    }
                    menuLoactionX = 0;
                }

            };
            th.start();
            th = null;
        }
    }
    
    private void close_Menu(){
        if (pnl_menu.getLocation().x == 0) {
            Thread th = new Thread() {
                @Override
                public void run() {
                    for (int i = 0; i >= -236; i--) {
                        pnl_menu.setLocation(i, 0);
                    }
                    menuLoactionX = -236;
                }

            };
            th.start();
            try {
                th.join();
            } catch (InterruptedException ex) {
                Logger.getLogger(Verwalten.class.getName()).log(Level.SEVERE, null, ex);
            }
            th = null;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Verwalten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Verwalten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Verwalten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Verwalten.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {

            Verwalten verwalten = new Verwalten();
            verwalten.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private palatte.Custom_button cbtn_close;
    private palatte.Custom_button cbtn_minimize;
    private palatte.Custom_cbb ccbb_Lop_chon_nganh;
    private palatte.Custom_cbb ccbb_SV_chon_gioi_tinh;
    private palatte.Custom_cbb ccbb_SVchon_lop;
    private palatte.Custom_cbb ccbb_SVchon_nganh;
    private palatte.Custom_cbb ccbb_SVchon_xep_hang;
    private palatte.Custom_cbb ccbb_chon_gioi_tinh_GV;
    private palatte.Custom_menu_button cmbtn_add_GV;
    private palatte.Custom_menu_button cmbtn_add_lop;
    private palatte.Custom_menu_button cmbtn_add_mon_hoc;
    private palatte.Custom_menu_button cmbtn_add_nganh_hoc;
    private palatte.Custom_menu_button cmbtn_add_sv;
    private palatte.Custom_menu_button cmbtn_chi_tiet_GV;
    private palatte.Custom_menu_button cmbtn_chi_tiet_lop;
    private palatte.Custom_menu_button cmbtn_chi_tiet_mon_hoc;
    private palatte.Custom_menu_button cmbtn_chi_tiet_nganh_hoc;
    private palatte.Custom_menu_button cmbtn_chi_tiet_sv;
    private palatte.Custom_menu_button cmbtn_giao_vien;
    private palatte.Custom_menu_button cmbtn_lop;
    private palatte.Custom_menu_button cmbtn_menu;
    private palatte.Custom_menu_button cmbtn_menu1;
    private palatte.Custom_menu_button cmbtn_mon;
    private palatte.Custom_menu_button cmbtn_nganh;
    private palatte.Custom_menu_button cmbtn_sinh_vien;
    private palatte.Custom_menu_button cmbtn_sx_GV;
    private palatte.Custom_menu_button cmbtn_sx_sv;
    private palatte.Custom_menu_button cmbtn_trang_chu;
    private palatte.Custom_menu_button cmbtn_xoa_GV;
    private palatte.Custom_menu_button cmbtn_xoa_lop;
    private palatte.Custom_menu_button cmbtn_xoa_mon_hoc;
    private palatte.Custom_menu_button cmbtn_xoa_nganh_hoc;
    private palatte.Custom_menu_button cmbtn_xoa_sv;
    private palatte.Custom_tb ctb_GV;
    private palatte.Custom_tb ctb_lop;
    private palatte.Custom_tb ctb_nganh;
    private palatte.Custom_tb ctb_sv;
    private palatte.Custom_tb custom_tb1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_giao_vien;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_lop_hoc;
    private javax.swing.JLabel lbl_mon_hoc;
    private javax.swing.JLabel lbl_nganh_hoc;
    private javax.swing.JLabel lbl_sinh_vien;
    private javax.swing.JLabel lbl_txt_giao_vien;
    private javax.swing.JLabel lbl_txt_giao_vien1;
    private javax.swing.JLabel lbl_txt_lop;
    private javax.swing.JLabel lbl_txt_lop1;
    private javax.swing.JLabel lbl_txt_mon;
    private javax.swing.JLabel lbl_txt_mon1;
    private javax.swing.JLabel lbl_txt_nganh;
    private javax.swing.JLabel lbl_txt_nganh1;
    private javax.swing.JLabel lbl_txt_sinh_vien;
    private javax.swing.JLabel lbl_txt_sinh_vien1;
    private javax.swing.JPanel pnl_content;
    private javax.swing.JPanel pnl_giao_vien;
    private javax.swing.JPanel pnl_header;
    private javax.swing.JPanel pnl_home;
    private javax.swing.JPanel pnl_lop;
    private javax.swing.JPanel pnl_main;
    private javax.swing.JPanel pnl_menu;
    private javax.swing.JPanel pnl_mon_hoc;
    private javax.swing.JPanel pnl_nganh_hoc;
    private javax.swing.JPanel pnl_sinh_vien;
    private javax.swing.JPanel pnl_taskbar;
    private javax.swing.JScrollPane spnl_GV;
    private javax.swing.JScrollPane spnl_lop;
    private javax.swing.JScrollPane spnl_mon_hoc;
    private javax.swing.JScrollPane spnl_nganh;
    private javax.swing.JScrollPane spnl_sv;
    private javax.swing.JTabbedPane tbpnl_main;
    // End of variables declaration//GEN-END:variables
}
